import Providers from '@/components/Providers';
// import './globals.css';
import { Inter } from 'next/font/google';
import React from 'react';


export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function Layout({children}: { children: React.ReactNode; }) {
    return (
        <div className={'flex justify-center w-screen h-screen overflow-hidden'}>
        {children}
            </div>
    );
}
