"use client";
import Providers from '@/components/Providers';
// import './globals.css';
import { Inter } from 'next/font/google';
import React from 'react';
import useBackgroundBlur from "@/lib/zustand/useBacgroundBlur";


// export const metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// };

export default function Layout({children}: { children: React.ReactNode; }) {
    // @ts-ignore
    // const blur = useBackgroundBlur(state => state.blur);
    return (children);
}
