'use client';
// import './globals.css';
import React from 'react';

// export const metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// };

export default function Layout({ children }: { children: React.ReactNode }) {
  // @ts-ignore
  // const blur = useBackgroundBlur(state => state.blur);
  return children;
}
